"""
achaim_wrapper.py
=================
Wrapper for the A-CHAIM C executable used in the DRDO SSL hybrid model.
Calls the binary via subprocess, writes ACHAIM.in, reads ACHAIMChars.out.

Usage:
    from models.achaim import get_achaim_hmf2
    result = get_achaim_hmf2(lat=65.0, lon=-100.0, db_path="...", exe_path="...")
    hmf2 = result['hmf2']  # km

Note: Only valid for |lat| >= ~55 degrees (A-CHAIM boundary).
The exe needs BOTH the assimilation .db (e.g. example.db) AND ECHAIM_FIRI.db
present in its working directory.
"""

import os
import shutil
import subprocess
import tempfile


def get_achaim_hmf2(lat, lon, db_path, exe_path, dregion=1, aurora=1, proton=1):
    """
    Query A-CHAIM for ionospheric characteristics at a single lat/lon point.

    Returns dict with keys: 'hmf2', 'nmf2', 'hbot', 'htop', 'hf1', 'he', 'hmf1'
    Returns None if call fails or point is outside A-CHAIM boundary.
    """

    # ── Validate paths ──────────────────────────────────────────────────────
    if not os.path.isfile(exe_path):
        print(f"[achaim_wrapper] ERROR: Executable not found: {exe_path}")
        return None

    if not os.path.isfile(db_path):
        print(f"[achaim_wrapper] ERROR: DB file not found: {db_path}")
        return None

    # ── Isolated temp directory per call ───────────────────────────────────
    with tempfile.TemporaryDirectory() as tmpdir:

        # ── Step 1: Copy assimilation DB into temp dir ─────────────────────
        db_filename = os.path.basename(db_path)
        tmp_db_path = os.path.join(tmpdir, db_filename)
        shutil.copy2(db_path, tmp_db_path)

        # ── Step 1b: Copy ECHAIM_FIRI.db into temp dir too ─────────────────
        # The exe also needs the FIRI background file in its working directory.
        # It lives next to the exe (in the ACHAIM folder).
        exe_dir = os.path.dirname(exe_path)
        firi_src = os.path.join(exe_dir, "ECHAIM_FIRI.db")
        if os.path.isfile(firi_src):
            shutil.copy2(firi_src, os.path.join(tmpdir, "ECHAIM_FIRI.db"))
        else:
            print(f"[achaim_wrapper] WARNING: ECHAIM_FIRI.db not found next to exe at {firi_src}")

        # ── Step 2: Write ACHAIM.in ─────────────────────────────────────────
        # interval=0 → exact values; alt=0 → TEC mode (characteristics only)
        achaim_in = (
            "# Auto-generated by achaim_wrapper.py\n"
            "# END HEADER\n"
            f"0 {lat}\n"
            f"0 {lon}\n"
            f"0 0\n"
            f"{dregion}\n"
            f"{aurora}\n"
            f"{proton}\n"
            f"{tmp_db_path}\n"
        )

        with open(os.path.join(tmpdir, "ACHAIM.in"), 'w') as f:
            f.write(achaim_in)

        # ── Step 3: Run the executable ──────────────────────────────────────
        # Add exe's own directory to PATH so Windows finds its MinGW DLLs
        env = os.environ.copy()
        env["PATH"] = exe_dir + os.pathsep + env.get("PATH", "")

        # Normalize path to native Windows format for subprocess
        exe_path_native = os.path.normpath(exe_path)

        # capture_output omitted: the 32-bit MinGW binary uses pthreads and
        # crashes (exit 3221225477) when run without a real console attached.
        try:
            proc = subprocess.run(
                [exe_path_native],
                cwd=tmpdir,
                timeout=30,
                env=env
            )
        except subprocess.TimeoutExpired:
            print("[achaim_wrapper] ERROR: ACHAIM timed out after 30s.")
            return None
        except Exception as e:
            print(f"[achaim_wrapper] ERROR: Could not run executable: {e}")
            return None

        if proc.returncode != 0:
            print(f"[achaim_wrapper] ERROR: ACHAIM exited with code {proc.returncode}")
            return None

        # ── Step 4: Parse ACHAIMChars.out ───────────────────────────────────
        out_file = os.path.join(tmpdir, "ACHAIMChars.out")

        if not os.path.isfile(out_file):
            print("[achaim_wrapper] ERROR: ACHAIMChars.out was not created.")
            return None

        characteristics = {}

        with open(out_file, 'r') as f:
            for line in f:
                line = line.strip()
                if not line or ':' not in line:
                    continue
                name, values_str = line.split(':', 1)
                name = name.strip().lower()
                values = values_str.strip().split()
                if not values:
                    characteristics[name] = None
                    continue
                try:
                    characteristics[name] = float(values[0])
                except ValueError:
                    characteristics[name] = None

        # ── Step 5: Validate result ─────────────────────────────────────────
        hmf2 = characteristics.get('hmf2')
        if hmf2 is None or hmf2 == 0.0:
            print(f"[achaim_wrapper] WARNING: hmf2={hmf2} — likely outside A-CHAIM boundary.")
            print(f"  lat={lat}, lon={lon}")
            return None

        return characteristics


def get_achaim_profile(lat, lon, db_path, exe_path):
    """
    Convenience wrapper matching hybrid_model.py interface.
    """
    result = get_achaim_hmf2(lat, lon, db_path, exe_path)

    if result is None:
        return None

    return {
        'hmF2' : result.get('hmf2'),
        'NmF2' : result.get('nmf2'),
        'HBot' : result.get('hbot'),
        'HTop' : result.get('htop'),
        'model': 'A-CHAIM'
    }


if __name__ == '__main__':

    EXE_PATH = "C:/Users/prith/Downloads/A-CHAIM_User_Release-6.0.3/A-CHAIM_User_Release-6.0.3/C/ACHAIM/ACHAIM.exe"
    DB_PATH  = "C:/Users/prith/Downloads/A-CHAIM_User_Release-6.0.3/A-CHAIM_User_Release-6.0.3/C/example/example.db"

    print("Testing A-CHAIM wrapper ...")
    print(f"  EXE : {EXE_PATH}")
    print(f"  DB  : {DB_PATH}\n")

    result = get_achaim_hmf2(lat=65.0, lon=-100.0, db_path=DB_PATH, exe_path=EXE_PATH)

    if result is None:
        print("Result: None — check paths or that point is inside A-CHAIM boundary.")
    else:
        units = {'nmf2': 'm⁻³', 'hmf2': 'km', 'hbot': 'km',
                 'htop': 'km', 'hf1': 'km', 'he': 'km', 'hmf1': 'km'}
        print("Result:")
        for key, val in result.items():
            print(f"  {key:6s}: {val:.4f} {units.get(key, '')}")